In [1]:
import numpy as np

# *Datatypes and Attributes*

In [8]:
# ndarray in the main datatype  of numpy
a1 = np.array([1,2,3,4,5])

In [9]:
a1

array([1, 2, 3, 4, 5])

In [15]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
a3 = np.array([[[1,2,3,4],
                [1,1,2,3],
                [1,2,3,5]],
               
                [[1,2,3,4],
                [1,1,2,3],
                [1,2,3,5]]])

In [17]:
a3

array([[[1, 2, 3, 4],
        [1, 1, 2, 3],
        [1, 2, 3, 5]],

       [[1, 2, 3, 4],
        [1, 1, 2, 3],
        [1, 2, 3, 5]]])

In [19]:
a1.shape

(5,)

In [20]:
a2.shape

(2, 4)

In [21]:
a3.shape

(2, 3, 4)

In [23]:
a = a1.ndim, a2.ndim, a3.ndim

In [24]:
a

(1, 2, 3)

In [27]:
type(a)

tuple

In [28]:
a1.dtype

dtype('int32')

In [1]:
x = (i for i in range(3))
for i in x:
    print(i)
for i in x:
    print(i)

0
1
2
