In [1]:
import numpy as np

# *Datatypes and Attributes*

In [2]:
# ndarray in the main datatype  of numpy
a1 = np.array([1,2,3,4,5])

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a3 = np.array([[[1,2,3,4],
                [1,1,2,3],
                [1,2,3,5]],
               
                [[1,2,3,4],
                [1,1,2,3],
                [1,2,3,5]]])

In [6]:
a3

array([[[1, 2, 3, 4],
        [1, 1, 2, 3],
        [1, 2, 3, 5]],

       [[1, 2, 3, 4],
        [1, 1, 2, 3],
        [1, 2, 3, 5]]])

In [7]:
a1.shape

(5,)

In [8]:
a2.shape

(2, 4)

In [9]:
a3.shape

(2, 3, 4)

In [10]:
a = a1.ndim, a2.ndim, a3.ndim

In [11]:
a

(1, 2, 3)

In [12]:
type(a)

tuple

In [13]:
a1.dtype

dtype('int32')

In [14]:
x = (i for i in range(3))
for i in x:
    print(i)
for i in x:
    print(i)

0
1
2


# ***Creating Arrays***

In [15]:
sample_arrays = np.array([1,2,3])

In [16]:
sample_arrays

array([1, 2, 3])

In [17]:
sample_arrays.dtype

dtype('int32')

In [18]:
ones = np.ones((3,3), 'int64')     #default is float64
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [19]:
ones.dtype

dtype('int64')

In [20]:
zeros = np.zeros((3,3), 'int64')
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [21]:
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [22]:
random_arr = np.random.randint(0, 10, size=(3,5))
random_arr

array([[5, 6, 3, 2, 6],
       [8, 5, 7, 6, 7],
       [5, 8, 4, 1, 4]])

In [23]:
random_arr_2 = np.random.random((3,5))

In [24]:
random_arr_2

array([[0.6429464 , 0.10591409, 0.90378308, 0.7057715 , 0.08828653],
       [0.46309044, 0.68820687, 0.01102463, 0.94033135, 0.82802949],
       [0.64049035, 0.66359879, 0.35529201, 0.16577359, 0.71066718]])

In [25]:
random_arr.size

15

In [26]:
random_arr.shape


(3, 5)

In [27]:
random_arr_3 = np.random.rand(5,3,3)
random_arr_3

array([[[0.44405887, 0.03195566, 0.48215005],
        [0.01160586, 0.26642983, 0.83169048],
        [0.71260409, 0.95413964, 0.81866019]],

       [[0.63230586, 0.25168964, 0.60303173],
        [0.6291115 , 0.45231532, 0.18122189],
        [0.74536742, 0.37057584, 0.80204086]],

       [[0.06530497, 0.7224004 , 0.5790138 ],
        [0.95182524, 0.12045602, 0.4393414 ],
        [0.88033902, 0.39002801, 0.74404043]],

       [[0.23103538, 0.12632756, 0.96682791],
        [0.31647626, 0.79294377, 0.69294731],
        [0.19630915, 0.29666744, 0.9967065 ]],

       [[0.15235855, 0.1212765 , 0.42101712],
        [0.87716084, 0.32848909, 0.91897053],
        [0.56666233, 0.80082601, 0.43674531]]])

In [28]:
# pseudo-random numbers
np.random.seed()

In [29]:
random_arr_4 = np.random.randint(10, size=(5,3))
random_arr_4

array([[3, 0, 5],
       [5, 9, 2],
       [5, 8, 6],
       [8, 2, 4],
       [3, 5, 4]])

In [30]:
# test = np.array(np.arange(0, 10, 2))
# test

# Viewing Arrays and Matrices

In [32]:
test = np.unique(random_arr_4)

In [34]:
print(list(test))

[0, 2, 3, 4, 5, 6, 8, 9]


In [45]:
test

array([0, 2, 3, 4, 5, 6, 8, 9])

In [36]:
a1

array([1, 2, 3, 4, 5])

In [37]:
a1[0]

1

In [38]:
a2[0]

array([1, 2, 3, 4])

In [39]:
a3[0]

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [1, 2, 3, 5]])

In [46]:
a3.shape

(2, 3, 4)

In [47]:
a3

array([[[1, 2, 3, 4],
        [1, 1, 2, 3],
        [1, 2, 3, 5]],

       [[1, 2, 3, 4],
        [1, 1, 2, 3],
        [1, 2, 3, 5]]])

In [48]:
a3[0]

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [1, 2, 3, 5]])

In [51]:
a3[1][]

SyntaxError: invalid syntax (1726033345.py, line 1)